### ISSUE TITLE
can i use your flxshadertoy shader for my haxelib?

### ISSUE THREAD

**Issue by ghost** [jobf/flixel-shadertoy-shader#4]
can i please use it i will put credit in the readme

**Comment by ghost** [comment]
https://lib.haxe.org/p/shadertools/ this is my haxelib

**Comment by jobf** [comment]
You can use it like a haxelib, check the readme for install instructions.

**Comment by ghost** [comment]
no i meant like can i use your flxshadertoy file for my haxelib

**Comment by ghost** [comment]
cause i think it whould be a good thing to add

**Comment by jobf** [comment]
You could have just used it like any other haxelib but I see you've copied it anyway.

**Comment by ghost** [comment]
lol sorry but i did put credit tho
